[project]
name = "mangersystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "pillow>=10.4.0",
    "waitress>=3.0.0",
]
